# --- 基础设置 ---
set -g status-style bg=default 
setw -g mode-keys vi

set -g status-right "#(hostname -I | awk '{print $1}') #(cat /sys/class/power_supply/BAT0/capacity)% %m-%d %H:%M"

# 4. 复制模式与粘贴 (Copy Mode)
# 建议：使用 Alt + v 进入复制模式，Alt + p 粘贴
bind -n M-v copy-mode
bind -n M-p paste-buffer

# 复制模式内部的按键 (Copy Mode VI key table)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i && tmux display-message 'Content copied to clipboard!'"
bind-key -T copy-mode-vi Escape send-keys -X cancel

# 5. 窗口管理 (Window Management)
# 重命名 -> Alt + r
bind -n M-r command-prompt -I "#W" "rename-window '%%'"

# 创建新窗口 -> Alt + c
bind -n M-c new-window -c "#{pane_current_path}"

# 关闭当前面板/窗口 -> Alt + x
bind -n M-x kill-pane

# 3. 快速重载配置文件 -> Alt + R (Shift + r)
bind -n M-R source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Alt + h/l 切换窗口 (不冲突，且手不用离开主键盘区)
bind -n M-h previous-window
bind -n M-l next-window

# --- 脚本与工具绑定 ---

bind -n M-q display-popup -E -w 60% -h 60% "bash $HOME/.config/tmux/scripts/quick-prompts/quick-prompts.sh"

bind -n M-w display-popup -E -w 60% -h 60% "bash $HOME/.config/tmux/scripts/quick-commands/quick-commands.sh"
